// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpdwvpwmvdhosihiyljg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwZHd2cHdtdmRob3NpaGl5bGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDExMzcsImV4cCI6MjA3MjIxNzEzN30.Y5s-lAt4DjLO7qTnk1ITDE4QnDN1dTpxN9HOrPONBPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});